name: Update database and version
on:
  # schedule:
  #   - cron: '0 0 * * 0'
  push

jobs: 
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with: 
          python-version: '3.x'
          
      - name: Run langnames.py
        run: |
          pip install pandas
          python langnames.py

 
      - name: Run versionbump.py
        id: versionbump
        run: echo "CHANGE=$(python c_i/versionbump.py)" >> $GITHUB_OUTPUT

      - name: Compile langnames.dtx
        if: steps.getchanges.outputs.CHANGES != 'no change'
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex

      - name: Compile langnames.dtx again
        if: steps.getchanges.outputs.CHANGES != 'no change'
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex

      - name: Commit changes
        if: steps.getchanges.outputs.CHANGES != 'no change'
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: "Automatically updated the database"
      
      - name: Zip Release
        if: steps.getchanges.outputs.CHANGES != 'no change'
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: langnames.zip
          path: langnames/*
          exclusions: '*-tags.tex *.aux *.glo *.hd *.idx *.log *.out *.synctex* *.toc'

      - name: CTAN submit
        if: steps.getchanges.outputs.CHANGES != 'no change'
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: validate
          file_path: langnames.zip  
          fields: |
            update: "true"
            pkg: langnames
            version: ${{ steps.versionbump.outputs.VERSION }}
            email: alejandrogarciaag41@gmail.com
            uploader: Alejandro García
