name: Update database and version
on:
  # schedule:
  #   - cron: '0 0 * * 0'
  push

jobs: 
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with: 
          python-version: '3.x'
          
      - name: Run langnames.py
        run: |
          pip install pandas
          python langnames.py

      - name: Changed Files
        uses: tj-actions/changed-files@v39.2.2
        with:
          files_yaml: |
            declarations:
              langnames/ln_*
 
      - name: Run versionbump.py
        id: versionbump
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        run: |
          echo "VERSION=$(python c_i/versionbump.py)" >> $GITHUB_OUTPUT

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: latex-action-2021-a 

      - name: Compile langnames.dtx
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: dante-ev/latex-action@latest
        with:  
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex

      - name: Commit changes
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: "Automatically updated the database"
      
      - name: Zip Release
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: langnames.zip
          path: langnames/*
          exclusions: '*-tags.tex *.aux *.glo *.hd *.idx *.log *.out *.synctex* *.toc'

      - name: CTAN submit
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: validate
          file_path: langnames.zip  
          fields: |
            update: "true"
            pkg: langnames
            version: ${{ steps.versionbump.outputs.VERSION }}
            author: Alejandro García Matarredona, निरंजन
            email: alejandrogarciaag41@gmail.com, hi.niranjan@pm.me 
            uploader: Alejandro García
