name: Update database and version
on:
  # schedule:
  #   - cron: '0 0 * * 0'
  push

jobs: 
  update_database:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionbump.outputs.VERSION }}
      changes: ${{ steps.versionbump.outputs.CHANGES }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with: 
          python-version: '3.x'
          
      - name: Run langnames.py
        run: |
          pip install pandas
          python langnames.py

      - name: Run versionbump.py
        id: versionbump
        run: python c_i/versionbump.py | awk 'FNR==1 {print "CHANGES="$0} FNR==2 {print "VERSION="$0}' >> "$GITHUB_OUTPUT"

  update_package:
    needs: update_database
    if: needs.update_database.outputs.changes != 'no change'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: ${{ needs.update_database.outputs.changes }} update in the package
          branch: auto-update
          reviewers: cicervlvs
