name: Update database and version
on:
  # schedule:
  #   - cron: '0 0 * * 0'
  push

jobs: 
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with: 
          python-version: '3.x'
          
      - name: Run langnames.py
        run: |
          pip install pandas
          python langnames.py

      - name: Run versionbump.py
        id: versionbump
        run: python c_i/versionbump.py | awk 'FNR==1 {print "CHANGES="$1} FNR==2 {print "VERSION="$1}' >> $GITHUB_OUTPUT

  update-package:
    if: ${{ steps.getchanges.outputs.CHANGES != 'no change' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile langnames.dtx
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex
          args: ""

      - name: Compile langnames.dtx again
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex
          args: ""

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: ${{ steps.getchanges.outputs.CHANGES }} update in the package
          branch: auto-update
          reviewers: cicervlvs
