name: Update database and version
on:
  # schedule:
  #   - cron: '0 0 * * 0'
  push

jobs: 
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with: 
          python-version: '3.x'
          
      - name: Run langnames.py
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          python langnames.py

      - name: Changed Files
        uses: tj-actions/changed-files@v39.2.2
        with:
          files_yaml: |
            declarations:
              latex/ln_*
 
      - name: Run versionbump.py
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        run: |
          echo "files have changed"
          python versionbump.py

      # Compile dtx file 
      - name: Compile langnames.dtx
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: dante-ev/latex-action@latest
        with:  
          root_file: latex/langnames.dtx
          args: '-lualatex\ -latexoption=-file-line-error\ -latexoption=-interaction=nonstopmode'
          extra_font_packages: c_i/shobhika

      - name: Commit changes
        # if: steps.changed-files-yaml.declarations.test_any_changed == 'true'
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: "Automatically updated the database"
            
# run langnames.py which generates the key-value pair files
# if there is a difference between the new and old files:
# replace old file with new file
# - bump up the version of the package
#  - change the version in the documentation file
#  - run the documentation file
# - create a new release?
# - notify me
# else:
# - do nothing
#
