name: Compile latex
on:
  push:

jobs:
  compile-latex:
   runs-on: ubuntu-latest
   steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile langnames.dtx
      uses: dante-ev/latex-action@latest
      with:
        working_directory: langnames
        root_file: langnames.dtx
        args: "-lualatex -r ../c_i/latexmkrc"
