# If pull request is accepted:
# package release
# make new release with tag
# publish on CTAN
name: publish update
on:
  pull_request:
    types:
      - closed

jobs:
  publish-update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.getversion.outputs.VERSION }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get version
        id: getversion
        run: echo "VERSION="$(python c_i/versionbump.py --current_version) >> "$GITHUB_OUTPUT"

      - name: Compile langnames.dtx
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex
          args: ""

      - name: Compile langnames.dtx again
        uses: dante-ev/latex-action@latest
        with:
          working_directory: langnames
          root_file: langnames.dtx
          compiler: lualatex
          args: ""

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: langnames.zip
          path: langnames/*
          exclusions: '*-tags.tex *.aux *.glo *.hd *.idx *.log *.out *.synctex* *.toc'

      - name: check zip file
        run: less langnames.zip
      # - name: GH Release
      #   uses: softprops/action-gh-release@v0.1.15

      - name: CTAN validate
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: validate
          file_path: langnames.zip
          fields: |
            update: "true"
            pkg: langnames
            version: ${{ steps.getversion.outputs.version }}
            email: alejandrogarciaag41@gmail.com
            uploader: Alejandro García
